import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from './header';
import Footer from './footer';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div id="__next" className="flex flex-col min-h-screen">
          <Header />
          <main className="flex-grow flex items-center justify-center bg-gradient-to-r from-blue-900 to-teal-400">
            <div className="w-full max-w-7xl p-8">
              {children}
            </div>
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}